version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: carteirinha
      MYSQL_DATABASE: carteirinha
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
